/* 
	the format of the tree definition file is simple,
	you can find specification in the Tigra Menu documentation at:
	
	http://www.softcomplex.com/products/tigra_menu/docs/items.html
Syntax for structures:
var TREE_ITEMS = [
	['item_name', 'url',
		['subitem_name', 'url'],
	],
];
*/

var TREE_ITEMS = [
	['AVRbeginners.net', 'intro.html',
		['Getting Started', 'getting_started/starter_2.html'],
		['AVR Assembler', '',
			['About AVR Assembler', 'assembler/start.html'],
			['Flow Charts', 'assembler/flow.html'],
			['MCU Status', 'assembler/mcustat.html'],
			['Math...', '',
				['Simple Maths', 'assembler/math/math.html'],
				['Multiple Byte Maths', 'assembler/math/multiple_math.html'],
			],
			['Jumps / Subroutine Calls', '',
				['Jump varieties', 'assembler/jump/jump.html'],
				['Call varieties', 'assembler/jump/call.html'],
				['More on indirect jumps', 'assembler/jump/indirect.html'],
			],
			['Conditional Branches/Loops', '',
				['Branches Introduction', 'assembler/branches/branch.html'],
				['Case Structures', 'assembler/branches/case.html'],
				['For Loops', 'assembler/branches/for.html'],
				['While Loops', 'assembler/branches/while.html'],
			],
			['Macros', 'assembler/macros.html'],
			['Directives/Expressions', 'assembler/directives.html'],
		],
		['Converting Numbers (Also asm)', '',
			['Overview', 'conversions/start.html'],
			['Number Formats', 'conversions/formats.html'],
			['Ascii Table', 'conversions/ascii.html'],
			['Int to...', '',
				['ASCII Coded Decimal', 'conversions/itoacd.html'],
				['ASCII Coded Hex', 'conversions/itoach.html'],
				['ASCII Coded Binary', 'conversions/itoacb.html'],
				['BCD', 'conversions/itobcd.html'],
			],
			['To Int From...', '',
				['ASCII Coded Decimal', 'conversions/acdtoi.html'],
				['ASCII Coded Hex', 'conversions/achtoi.html'],
				['ASCII Coded Binary', 'conversions/acbtoi.html'],
				['BCD', 'conversions/bcdtoi.html'],
			],
		],
		['AVR Architecture', 'architecture/start.html',
			['ALU', 'architecture/alu/alu.html'],
			['SRAM and Flash', '',
				['General Description', 'architecture/sram_flash/sram.html'],
				['SRAM and Flash operations', 'architecture/sram_flash/sram_ops.html'],
				['Lookup Tables', 'architecture/sram_flash/tables.html'],
				['Working With Strings', 'architecture/sram_flash/strings.html'],
				['Mem Copy Routines', 'architecture/sram_flash/memcopy.html'],
			],
			['The Stack', '',
				['General Description', 'architecture/stack/stack.html'],
				['Subroutines', 'architecture/stack/routines.html'],
			],
			['Interrupts', 'architecture/int/int.html'],
			['I/O Ports', '',
				['General Description', 'architecture/ioports/ioports.html'],
				['I/O Instructions', 'architecture/ioports/io_instr.html'],
			],
			['Timers', '',
				['General Description', 'architecture/timers/timers.html'],
				['Setting up a Timer', 'architecture/timers/setup_timer.html'],
				['Flashing LED', 'architecture/timers/led_timer.html'],
				['PWM LED demo', 'architecture/timers/pwm_led.html'],
			],
			['EEPROM', 'architecture/eeprom/eeprom.html'],
			['SPI', 'architecture/spi/spi.html'],
			['UART', '',
				['General Description', 'architecture/uart/uart.html'],
				['Setting up The UART', 'architecture/uart/setup_uart.html'],
				['UART ascii to hex Converter', 'architecture/uart/uart_atoh.html'],
				['UART FIFO Buffer', 'architecture/uart/uart_buffer.html'],
			],
			['Analog Comparator', 'architecture/ana_comp/ana_comp.html'],
			['AD Converter', '',
				['General Description', 'architecture/adc/adc.html'],
				['mega8 ADC example', 'architecture/adc/m8_adc_example.html'],
			],
			['Fuses', 'architecture/fuses/fuses.html'],
			['Lock Bits', 'architecture/lock_bits/lock_bits.html'],
			['Watch Dog Timer', '',
				['General Description', 'architecture/wdt/wdt.html'],
				['WDT Demo Code', 'architecture/wdt/wdt_demo.html'],
			],
		],
/*		['Advanced Assembler', '',
			['Indirect call/jump', 'advanced_asm/indirect.html'],
			['Buffers and Queues', 'advanced_asm/buffers.html'],
		],
*/
		['Software', '',
			['AVR Calc', 'software/avrcalc.html'],
			['AVR Studio', 'studio/intro.html',
				['Creating a New Project', 'studio/new_project.html']
			],
			['Terminal Program', 'software/terminal.html'],
		],
		['ATmega8 Dev Board', '',
			['General Description', 'm8_board/intro.html']
		],
	],
];

